spring.application.name=backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/athlix_db
spring.datasource.username=postgres
spring.datasource.password=Athlix@upes2026

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries in Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080